# Support me on GitHub Sponsors and Buy Me a Coffee!
# Developed and maintained by zeroxpapone
# Github Sponsors: https://github.com/sponsors/zeroxpapone
# Buy Me a Coffee: https://www.buymeacoffee.com/zeroxpapone

github: zeroxpapone
buymeacoffee: zeroxpapone
# Your support helps me to keep improving my projects and creating new ones.
# Sponsoring this project means a lot and motivates me to continue my work.
# Thank you for your generosity and support!
